# This workflow is used to build all the wheels and source distributions for
# the project and, on tags and releases, upload them. It is enabled on every
# commit to ensure that the wheels can be built on all platforms, but releases
# are only triggered in two situations:
#
# 1. When a tag is created, the workflow will upload the package to
#    test.pypi.org.
# 2. When a release is made, the workflow will upload the package to pypi.org.
#
# It is done this way until PyPI has draft reviews, to allow for a two-stage
# upload with a chance for manual intervention before the final publication.
name: Build

on:
  push:

jobs:
  build_linuxarm64_wheels:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        platform:
          - 'manylinux2014_aarch64'
    name: Build a ${{ matrix.platform }} for ${{ matrix.python_tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        if: ${{ matrix.platform == 'manylinux2014_aarch64' }}
        name: Set up QEMU
      - name: Install docker image
        run: |
          DOCKER_IMAGE="quay.io/pypa/${{ matrix.platform }}"
          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_ENV
          docker pull $DOCKER_IMAGE
      - name: Build wheels
        env:
          PYTHON_TAGS: "cp36-cp36m cp37-cp37m cp38-cp38"
          PRE_CMD:  ${{ matrix.platform == 'manylinux1_i686' && 'linux32' || '' }}
        run: |
          echo "$name"
          docker run --rm \
            -e PLAT=${{ matrix.platform }} \
            -e PYTHON_TAGS="$PYTHON_TAGS" \
            -v `pwd`:/io "$DOCKER_IMAGE" \
            $PRE_CMD \
            /io/scripts/build_manylinux_wheels.sh
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
